name: Build Windows Standalone

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Download and Extract ONNX Runtime
      run: |
        mkdir -p _deps
        Invoke-WebRequest -Uri "https://github.com/microsoft/onnxruntime/releases/download/v1.18.0/onnxruntime-win-x64-1.18.0.zip" -OutFile "onnxruntime.zip"
        Expand-Archive -Path "onnxruntime.zip" -DestinationPath "_deps"
        Rename-Item -Path "_deps\onnxruntime-win-x64-1.18.0" -NewName "onnxruntime"

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build Project
      run: cmake --build build --config Release

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: SubverseLabSplitter-Windows
        path: build/SubverseSplitter_artefacts/**/Standalone/*
